// Skill Update Types — Living Skill System
// Mirrors the AKL UpdateCard pattern. Skills start from roleSkills.ts (Canon)
// and evolve via SkillUpdateCards generated by the AKL, peer review, and feedback.

export type SkillUpdateType =
  | "refinement"       // Makes an existing heuristic more precise
  | "new_heuristic"    // Brand new rule of thumb discovered from usage
  | "failure_mode"     // New failure pattern detected
  | "framework_update" // Existing framework updated with new insight;

export interface SkillUpdateCard {
  id: string;
  role: string;
  skillName: string;                    // Which mental framework or heuristic this updates
  updateType: SkillUpdateType;
  content: string;                      // Text injected into practitioner skills prompt
  evidence: string[];                   // Event IDs / message IDs that triggered this
  confidence: number;                   // 0.0 - 1.0
  usageCount: number;                   // How many times this skill was active in a response
  successRate: number;                  // Ratio of positive feedback when this skill was active
  promoted: boolean;                    // Promoted to Canon (merged into roleSkills.ts base)
  createdAt: string;                    // ISO timestamp
  expiryDate: string;                   // ISO timestamp — cards expire after 30 days by default
  lastUsedAt?: string;                  // ISO timestamp of last usage
}

export const SKILL_UPDATE_EXPIRY_DAYS = 30;
export const SKILL_UPDATE_CONFIDENCE_THRESHOLD = 0.62; // Below this = worth updating
export const SKILL_PROMOTION_SUCCESS_RATE = 0.72;      // Above this = promote to Canon
export const MAX_ACTIVE_UPDATES_PER_ROLE = 10;         // Prevent unbounded growth
