import { ShieldCheck } from 'lucide-react';
import { EmptyState } from '@/components/ui/EmptyState';

/**
 * Empty state for the Approvals tab.
 *
 * Shown when there are no pending approvals. No CTA button — approvals are
 * system-generated by the autonomy pipeline, not user-initiated.
 */
export function ApprovalsEmptyState() {
  return (
    <div aria-live="polite">
      <EmptyState
        icon={ShieldCheck}
        title="Nothing needs your approval"
        description="When a Hatch starts something that needs a sign-off, it'll show up here. You're in control of what gets acted on."
      />
    </div>
  );
}
